// lingua-ai-vue3/src/pages/HomePage.vue
<template>
  <div class="min-h-screen bg-white dark:bg-gray-950">
    <Navbar />
    <main>
      <Hero />
      <Features />
      <Localization />
      <CTA />
    </main>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import Navbar from '../components/Navbar.vue';
import Hero from '../components/Hero.vue';
import Features from '../components/Features.vue';
import Localization from '../components/Localization.vue';
import CTA from '../components/CTA.vue';
import Footer from '../components/Footer.vue';
</script>

// lingua-ai/src/pages/HomePage.tsx
import { Navbar } from '../components/Navbar';
import { Hero } from '../components/Hero';
import { Features } from '../components/Features';
import { Localization } from '../components/Localization';
import { CTA } from '../components/CTA';
import { Footer } from '../components/Footer';

export function HomePage() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-950">
      <Navbar />
      <main>
        <Hero />
        <Features />
        <Localization />
        <CTA />
      </main>
      <Footer />
    </div>
  );
}
