// lingua-ai-vue3/src/App.vue
<template>
  <router-view />
</template>

<script setup lang="ts">
import { computed, watch } from 'vue';
import { useAppStore } from './stores/appStore';

const store = useAppStore();
const theme = computed(() => store.theme);

// Watch theme changes and apply to document
watch(theme, (newTheme) => {
  if (newTheme === 'dark') {
    document.documentElement.classList.add('dark');
  } else {
    document.documentElement.classList.remove('dark');
  }
}, { immediate: true });
</script>

// lingua-ai/src/App.tsx
import { createHashRouter, RouterProvider } from 'react-router-dom';
import { useEffect } from 'react';
import { useAppStore } from './stores/appStore';
import './i18n';
import './index.css';

// Pages
import { HomePage } from './pages/HomePage';
import { LoginPage } from './pages/LoginPage';
import { DashboardPage } from './pages/DashboardPage';
import { VocabularyPage } from './pages/VocabularyPage';

const router = createHashRouter([
  { path: '/', element: <HomePage /> },
  { path: '/login', element: <LoginPage /> },
  { path: '/register', element: <LoginPage /> },
  { path: '/dashboard', element: <DashboardPage /> },
  { path: '/vocabulary', element: <VocabularyPage /> },
]);

function App() {
  const { theme } = useAppStore();

  useEffect(() => {
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme]);

  return <RouterProvider router={router} />;
}

export default App;
