// linguaai-profile/pages/SocialPage.tsx
import React, { useState } from 'react';
import { 
  Trophy, 
  Flame, 
  UserPlus, 
  Share2, 
  Clock, 
  TrendingUp, 
  Globe, 
  Users, 
  Bell,
  Search,
  Settings,
  LogOut,
  ChevronRight,
  MoreHorizontal
} from 'lucide-react';

// Types
interface Friend {
  id: string;
  name: string;
  avatar: string;
  status: 'online' | 'offline' | 'studying';
  currentLesson: string;
  streak: number;
  level: number;
}

interface FriendRequest {
  id: string;
  name: string;
  avatar: string;
  mutualFriends: number;
}

// Mock Data
const friendsData: Friend[] = [
  { id: '1', name: 'Sarah Chen', avatar: 'SC', status: 'online', currentLesson: 'Spanish Basics', streak: 45, level: 12 },
  { id: '2', name: 'Mike Johnson', avatar: 'MJ', status: 'studying', currentLesson: 'French Grammar', streak: 32, level: 8 },
  { id: '3', name: 'Emma Wilson', avatar: 'EW', status: 'online', currentLesson: 'Japanese Kanji', streak: 67, level: 15 },
  { id: '4', name: 'David Kim', avatar: 'DK', status: 'offline', currentLesson: 'German Vocabulary', streak: 21, level: 6 },
  { id: '5', name: 'Lisa Anderson', avatar: 'LA', status: 'online', currentLesson: 'Italian Phrases', streak: 89, level: 18 },
  { id: '6', name: 'Tom Brown', avatar: 'TB', status: 'studying', currentLesson: 'Korean Alphabet', streak: 15, level: 4 },
];

const friendRequests: FriendRequest[] = [
  { id: '1', name: 'Alex Rivera', avatar: 'AR', mutualFriends: 3 },
  { id: '2', name: 'Jessica Lee', avatar: 'JL', mutualFriends: 5 },
];

// Components
const Header: React.FC = () => {
  return (
    <header className="sticky top-0 z-50 bg-white dark:bg-[#101922] border-b border-gray-200 dark:border-gray-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          {/* Logo */}
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-[#137fec] flex items-center justify-center">
              <Globe className="w-5 h-5 text-white" />
            </div>
            <span className="text-xl font-bold text-gray-900 dark:text-white">LinguaAI</span>
          </div>

          {/* Navigation */}
          <nav className="hidden md:flex items-center gap-8">
            <a href="#" className="text-gray-600 dark:text-gray-300 hover:text-[#137fec] dark:hover:text-[#137fec] transition-colors">Learn</a>
            <a href="#" className="text-[#137fec] font-medium">Social</a>
            <a href="#" className="text-gray-600 dark:text-gray-300 hover:text-[#137fec] dark:hover:text-[#137fec] transition-colors">Practice</a>
            <a href="#" className="text-gray-600 dark:text-gray-300 hover:text-[#137fec] dark:hover:text-[#137fec] transition-colors">Leaderboard</a>
          </nav>

          {/* Right Section */}
          <div className="flex items-center gap-4">
            {/* Streak Badge */}
            <div className="hidden sm:flex items-center gap-1.5 px-3 py-1.5 bg-orange-50 dark:bg-orange-900/20 rounded-full">
              <Flame className="w-4 h-4 text-orange-500" />
              <span className="text-sm font-semibold text-orange-600 dark:text-orange-400">12</span>
            </div>

            {/* User Avatar */}
            <div className="w-9 h-9 rounded-full bg-gradient-to-br from-[#137fec] to-blue-600 flex items-center justify-center cursor-pointer hover:ring-2 hover:ring-[#137fec] hover:ring-offset-2 dark:hover:ring-offset-[#101922] transition-all">
              <span className="text-sm font-medium text-white">JD</span>
            </div>
          </div>
        </div>
      </div>
    </header>
  );
};

const Sidebar: React.FC = () => {
  return (
    <aside className="w-full lg:w-80 space-y-6">
      {/* Invite Friends Card */}
      <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-[#137fec] to-blue-600 p-6 text-white">
        <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full -translate-y-1/2 translate-x-1/2" />
        <div className="relative z-10">
          <div className="w-12 h-12 rounded-xl bg-white/20 flex items-center justify-center mb-4">
            <Users className="w-6 h-6 text-white" />
          </div>
          <h3 className="text-lg font-bold mb-2">Invite Friends</h3>
          <p className="text-sm text-blue-100 mb-4">Learn together and earn bonus XP when they join!</p>
          <button className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-white text-[#137fec] rounded-xl font-semibold hover:bg-blue-50 transition-colors">
            <Share2 className="w-4 h-4" />
            Share Invite
          </button>
        </div>
      </div>

      {/* My Stats Card */}
      <div className="bg-white dark:bg-[#1a2632] rounded-2xl p-6 border border-gray-200 dark:border-gray-800">
        <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-4">My Stats</h3>
        
        <div className="space-y-4">
          {/* Level */}
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center">
                <Trophy className="w-5 h-5 text-purple-600 dark:text-purple-400" />
              </div>
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400">Level</p>
                <p className="text-lg font-bold text-gray-900 dark:text-white">15</p>
              </div>
            </div>
            <ChevronRight className="w-5 h-5 text-gray-400" />
          </div>

          {/* Streak */}
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-orange-100 dark:bg-orange-900/30 flex items-center justify-center">
                <Flame className="w-5 h-5 text-orange-600 dark:text-orange-400" />
              </div>
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400">Streak</p>
                <p className="text-lg font-bold text-gray-900 dark:text-white">12 days</p>
              </div>
            </div>
            <ChevronRight className="w-5 h-5 text-gray-400" />
          </div>

          {/* Weekly Progress */}
          <div className="pt-2">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <Clock className="w-4 h-4 text-gray-400" />
                <span className="text-sm text-gray-600 dark:text-gray-400">This Week</span>
              </div>
              <span className="text-sm font-semibold text-[#137fec]">4.5h / 7h</span>
            </div>
            <div className="h-2 bg-gray-100 dark:bg-gray-700 rounded-full overflow-hidden">
              <div className="h-full w-[64%] bg-gradient-to-r from-[#137fec] to-blue-400 rounded-full" />
            </div>
          </div>
        </div>
      </div>
    </aside>
  );
};

const FriendCard: React.FC<{ friend: Friend }> = ({ friend }) => {
  const statusColors = {
    online: 'bg-green-500',
    offline: 'bg-gray-400',
    studying: 'bg-[#137fec]'
  };

  const statusLabels = {
    online: 'Online',
    offline: 'Offline',
    studying: 'Studying'
  };

  return (
    <div className="bg-white dark:bg-[#1a2632] rounded-xl p-4 border border-gray-200 dark:border-gray-800 hover:border-[#137fec] dark:hover:border-[#137fec] transition-all hover:shadow-lg dark:hover:shadow-blue-900/20">
      <div className="flex items-start gap-4">
        {/* Avatar with Status */}
        <div className="relative">
          <div className="w-14 h-14 rounded-full bg-gradient-to-br from-gray-100 to-gray-200 dark:from-gray-700 dark:to-gray-600 flex items-center justify-center">
            <span className="text-lg font-semibold text-gray-600 dark:text-gray-300">{friend.avatar}</span>
          </div>
          <div className={`absolute bottom-0 right-0 w-4 h-4 ${statusColors[friend.status]} rounded-full border-2 border-white dark:border-[#1a2632]`} />
        </div>

        {/* Info */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center justify-between">
            <h4 className="font-semibold text-gray-900 dark:text-white truncate">{friend.name}</h4>
            <span className={`text-xs px-2 py-0.5 rounded-full ${
              friend.status === 'online' ? 'bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400' :
              friend.status === 'studying' ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400' :
              'bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-400'
            }`}>
              {statusLabels[friend.status]}
            </span>
          </div>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-0.5 truncate">{friend.currentLesson}</p>
          
          {/* Stats Row */}
          <div className="flex items-center gap-4 mt-3">
            <div className="flex items-center gap-1.5">
              <Flame className="w-4 h-4 text-orange-500" />
              <span className="text-sm font-medium text-gray-700 dark:text-gray-300">{friend.streak}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <Trophy className="w-4 h-4 text-purple-500" />
              <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Lvl {friend.level}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

const FriendRequestCard: React.FC<{ request: FriendRequest }> = ({ request }) => {
  return (
    <div className="bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 rounded-xl p-4 border border-blue-200 dark:border-blue-800">
      <div className="flex items-center gap-4">
        <div className="w-12 h-12 rounded-full bg-gradient-to-br from-[#137fec] to-blue-600 flex items-center justify-center">
          <span className="text-sm font-semibold text-white">{request.avatar}</span>
        </div>
        <div className="flex-1">
          <h4 className="font-semibold text-gray-900 dark:text-white">{request.name}</h4>
          <p className="text-sm text-gray-500 dark:text-gray-400">{request.mutualFriends} mutual friends</p>
        </div>
        <div className="flex items-center gap-2">
          <button className="px-4 py-2 bg-[#137fec] text-white rounded-lg text-sm font-medium hover:bg-blue-600 transition-colors">
            Accept
          </button>
          <button className="px-4 py-2 bg-white dark:bg-[#1a2632] text-gray-700 dark:text-gray-300 rounded-lg text-sm font-medium border border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors">
            Decline
          </button>
        </div>
      </div>
    </div>
  );
};

const Footer: React.FC = () => {
  return (
    <footer className="bg-white dark:bg-[#101922] border-t border-gray-200 dark:border-gray-800 mt-12">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded bg-[#137fec] flex items-center justify-center">
              <Globe className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="font-semibold text-gray-900 dark:text-white">LinguaAI</span>
          </div>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            © 2024 LinguaAI. Learn languages together.
          </p>
          <div className="flex items-center gap-6">
            <a href="#" className="text-sm text-gray-500 dark:text-gray-400 hover:text-[#137fec] transition-colors">Privacy</a>
            <a href="#" className="text-sm text-gray-500 dark:text-gray-400 hover:text-[#137fec] transition-colors">Terms</a>
            <a href="#" className="text-sm text-gray-500 dark:text-gray-400 hover:text-[#137fec] transition-colors">Help</a>
          </div>
        </div>
      </div>
    </footer>
  );
};

// Main Page Component
const SocialPage: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'friends' | 'requests' | 'leaderboard'>('friends');

  return (
    <div className="min-h-screen bg-[#f6f7f8] dark:bg-[#101922]">
      <Header />
      
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="flex flex-col lg:flex-row gap-8">
          {/* Sidebar */}
          <Sidebar />

          {/* Main Content */}
          <div className="flex-1">
            {/* Page Header */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
              <div>
                <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Social Hub</h1>
                <p className="text-gray-500 dark:text-gray-400 mt-1">Connect with friends and learn together</p>
              </div>
              <button className="flex items-center justify-center gap-2 px-4 py-2.5 bg-[#137fec] text-white rounded-xl font-semibold hover:bg-blue-600 transition-colors">
                <UserPlus className="w-5 h-5" />
                Add Friend
              </button>
            </div>

            {/* Tab Navigation */}
            <div className="flex items-center gap-1 p-1 bg-white dark:bg-[#1a2632] rounded-xl border border-gray-200 dark:border-gray-800 mb-6">
              <button
                onClick={() => setActiveTab('friends')}
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition-all ${
                  activeTab === 'friends'
                    ? 'bg-[#137fec] text-white'
                    : 'text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800'
                }`}
              >
                <Users className="w-4 h-4" />
                Friends
                <span className="px-2 py-0.5 bg-white/20 rounded-full text-xs">6</span>
              </button>
              <button
                onClick={() => setActiveTab('requests')}
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition-all ${
                  activeTab === 'requests'
                    ? 'bg-[#137fec] text-white'
                    : 'text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800'
                }`}
              >
                <Bell className="w-4 h-4" />
                Requests
                <span className="px-2 py-0.5 bg-red-500 text-white rounded-full text-xs">2</span>
              </button>
              <button
                onClick={() => setActiveTab('leaderboard')}
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition-all ${
                  activeTab === 'leaderboard'
                    ? 'bg-[#137fec] text-white'
                    : 'text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800'
                }`}
              >
                <TrendingUp className="w-4 h-4" />
                Global
              </button>
            </div>

            {/* Tab Content */}
            {activeTab === 'friends' && (
              <div className="space-y-4">
                {/* Friend Requests Notification */}
                {friendRequests.length > 0 && (
                  <div className="mb-6">
                    <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3 flex items-center gap-2">
                      <Bell className="w-4 h-4 text-[#137fec]" />
                      Friend Requests ({friendRequests.length})
                    </h3>
                    <div className="space-y-3">
                      {friendRequests.map(request => (
                        <FriendRequestCard key={request.id} request={request} />
                      ))}
                    </div>
                  </div>
                )}

                {/* Friends Grid */}
                <div>
                  <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">All Friends</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {friendsData.map(friend => (
                      <FriendCard key={friend.id} friend={friend} />
                    ))}
                  </div>
                </div>
              </div>
            )}

            {activeTab === 'requests' && (
              <div className="space-y-4">
                <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">Pending Requests</h3>
                <div className="space-y-3">
                  {friendRequests.map(request => (
                    <FriendRequestCard key={request.id} request={request} />
                  ))}
                </div>
              </div>
            )}

            {activeTab === 'leaderboard' && (
              <div className="bg-white dark:bg-[#1a2632] rounded-2xl p-6 border border-gray-200 dark:border-gray-800">
                <div className="text-center py-12">
                  <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center">
                    <Trophy className="w-8 h-8 text-[#137fec]" />
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Global Leaderboard</h3>
                  <p className="text-gray-500 dark:text-gray-400">Compete with learners worldwide. Coming soon!</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default SocialPage;

// lingua-ai-vue3/src/pages/SocialPage.vue
<template>
  <div class="min-h-screen bg-background-light dark:bg-background-dark">
    <!-- Header -->
    <header class="bg-surface-light dark:bg-surface-dark border-b border-border-light dark:border-border-dark sticky top-0 z-50">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-4">
            <div class="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-primary-dark flex items-center justify-center text-white font-bold">
              {{ user?.name?.[0] || 'U' }}
            </div>
            <h1 class="text-xl font-bold text-text-main dark:text-text-main-dark">社交中心</h1>
          </div>
          <div class="flex items-center gap-2">
            <button class="p-2 rounded-xl hover:bg-background-light dark:hover:bg-card-dark transition-colors relative">
              <MessageCircle class="w-5 h-5 text-text-secondary dark:text-text-secondary-dark" />
              <span class="absolute top-1 right-1 w-2 h-2 bg-red-500 rounded-full" />
            </button>
            <button class="px-4 py-2 rounded-xl bg-primary text-white text-sm font-medium hover:bg-primary-dark transition-colors flex items-center gap-2">
              <UserPlus class="w-4 h-4" />
              添加好友
            </button>
          </div>
        </div>
      </div>
    </header>

    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Tabs -->
      <div class="flex gap-2 mb-6 overflow-x-auto pb-2">
        <button
          v-for="tab in tabs"
          :key="tab.id"
          @click="activeTab = tab.id"
          :class="[
            'px-4 py-2 rounded-xl font-medium flex items-center gap-2 transition-all whitespace-nowrap',
            activeTab === tab.id
              ? 'bg-primary text-white shadow-lg shadow-primary/30'
              : 'bg-surface-light dark:bg-surface-dark text-text-secondary dark:text-text-secondary-dark hover:bg-background-light dark:hover:bg-card-dark'
          ]"
        >
          <component :is="tab.icon" class="w-4 h-4" />
          {{ tab.label }}
        </button>
      </div>

      <!-- Friends Tab -->
      <div v-if="activeTab === 'friends'" class="grid lg:grid-cols-3 gap-6">
        <div class="lg:col-span-2">
          <!-- Search -->
          <div class="bg-surface-light dark:bg-surface-dark rounded-2xl p-4 border border-border-light dark:border-border-dark mb-6">
            <div class="relative">
              <Search class="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-text-secondary dark:text-text-secondary-dark" />
              <input
                v-model="searchQuery"
                type="text"
                placeholder="搜索好友..."
                class="w-full pl-12 pr-4 py-3 rounded-xl bg-background-light dark:bg-card-dark border border-border-light dark:border-border-dark text-text-main dark:text-text-main-dark placeholder-text-secondary dark:placeholder-text-secondary-dark focus:outline-none focus:border-primary"
              />
            </div>
          </div>

          <!-- Friends Grid -->
          <div class="grid sm:grid-cols-2 gap-4">
            <!-- FriendCard inline -->
            <div
              v-for="friend in filteredFriends"
              :key="friend.name"
              class="bg-surface-light dark:bg-surface-dark rounded-2xl p-4 border border-border-light dark:border-border-dark hover:shadow-lg transition-all duration-300"
            >
              <div class="flex items-center gap-3">
                <div class="relative">
                  <div class="w-12 h-12 rounded-full bg-gradient-to-br from-primary to-primary-dark flex items-center justify-center text-white font-bold">
                    {{ friend.avatar }}
                  </div>
                  <div
                    :class="[
                      'absolute bottom-0 right-0 w-3.5 h-3.5 rounded-full border-2 border-surface-light dark:border-surface-dark',
                      friend.isOnline ? 'bg-green-500' : 'bg-gray-400'
                    ]"
                  />
                </div>
                <div class="flex-1 min-w-0">
                  <h4 class="font-semibold text-text-main dark:text-text-main-dark truncate">{{ friend.name }}</h4>
                  <div class="flex items-center gap-2 text-xs text-text-secondary dark:text-text-secondary-dark">
                    <span>Lv.{{ friend.level }}</span>
                    <span>·</span>
                    <span>{{ friend.xp.toLocaleString() }} XP</span>
                  </div>
                </div>
              </div>

              <div class="flex items-center justify-between mt-4">
                <div class="flex items-center gap-1 text-orange-500">
                  <Flame class="w-4 h-4" />
                  <span class="text-sm font-medium">{{ friend.streak }} 天</span>
                </div>
                <span v-if="!friend.isOnline && friend.lastActive" class="text-xs text-text-secondary dark:text-text-secondary-dark">{{ friend.lastActive }}</span>
              </div>

              <div class="flex gap-2 mt-4">
                <button class="flex-1 py-2 rounded-xl bg-primary/10 dark:bg-primary/20 text-primary text-sm font-medium hover:bg-primary/20 dark:hover:bg-primary/30 transition-colors flex items-center justify-center gap-1">
                  <MessageCircle class="w-4 h-4" />
                  发消息
                </button>
                <button class="px-3 py-2 rounded-xl border border-border-light dark:border-border-dark text-text-secondary dark:text-text-secondary-dark hover:bg-background-light dark:hover:bg-card-dark transition-colors">
                  <MoreHorizontal class="w-4 h-4" />
                </button>
              </div>
            </div>
          </div>
        </div>

        <!-- Sidebar -->
        <div class="space-y-6">
          <!-- My Stats -->
          <div class="bg-surface-light dark:bg-surface-dark rounded-2xl p-6 border border-border-light dark:border-border-dark">
            <h3 class="font-bold text-text-main dark:text-text-main-dark mb-4">我的社交数据</h3>
            <div class="space-y-4">
              <div class="flex items-center justify-between">
                <span class="text-text-secondary dark:text-text-secondary-dark">好友数量</span>
                <span class="font-semibold text-text-main dark:text-text-main-dark">{{ friends.length }}</span>
              </div>
              <div class="flex items-center justify-between">
                <span class="text-text-secondary dark:text-text-secondary-dark">全球排名</span>
                <span class="font-semibold text-text-main dark:text-text-main-dark">#420</span>
              </div>
              <div class="flex items-center justify-between">
                <span class="text-text-secondary dark:text-text-secondary-dark">获得点赞</span>
                <span class="font-semibold text-text-main dark:text-text-main-dark">1,234</span>
              </div>
            </div>
          </div>

          <!-- Suggested Friends -->
          <div class="bg-surface-light dark:bg-surface-dark rounded-2xl p-6 border border-border-light dark:border-border-dark">
            <h3 class="font-bold text-text-main dark:text-text-main-dark mb-4">推荐好友</h3>
            <div class="space-y-3">
              <div
                v-for="person in suggestedFriends"
                :key="person.name"
                class="flex items-center gap-3"
              >
                <div class="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-primary-dark flex items-center justify-center text-white font-bold text-sm">
                  {{ person.avatar }}
                </div>
                <div class="flex-1">
                  <p class="font-medium text-text-main dark:text-text-main-dark text-sm">{{ person.name }}</p>
                  <p class="text-xs text-text-secondary dark:text-text-secondary-dark">Lv.{{ person.level }}</p>
                </div>
                <button class="p-2 rounded-xl bg-primary/10 dark:bg-primary/20 text-primary hover:bg-primary/20 dark:hover:bg-primary/30 transition-colors">
                  <UserPlus class="w-4 h-4" />
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Feed Tab -->
      <div v-if="activeTab === 'feed'" class="grid lg:grid-cols-3 gap-6">
        <div class="lg:col-span-2 space-y-6">
          <!-- Create Post -->
          <div class="bg-surface-light dark:bg-surface-dark rounded-2xl p-6 border border-border-light dark:border-border-dark">
            <div class="flex gap-4">
              <div class="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-primary-dark flex items-center justify-center text-white font-bold flex-shrink-0">
                {{ user?.name?.[0] || 'U' }}
              </div>
              <div class="flex-1">
                <textarea
                  placeholder="分享你的学习心得..."
                  class="w-full p-3 rounded-xl bg-background-light dark:bg-card-dark border border-border-light dark:border-border-dark text-text-main dark:text-text-main-dark placeholder-text-secondary dark:placeholder-text-secondary-dark resize-none focus:outline-none focus:border-primary"
                  rows="3"
                />
                <div class="flex items-center justify-between mt-3">
                  <div class="flex gap-2">
                    <button class="p-2 rounded-xl hover:bg-background-light dark:hover:bg-card-dark transition-colors text-text-secondary dark:text-text-secondary-dark">
                      📷 图片
                    </button>
                    <button class="p-2 rounded-xl hover:bg-background-light dark:hover:bg-card-dark transition-colors text-text-secondary dark:text-text-secondary-dark">
                      🏷️ 标签
                    </button>
                  </div>
                  <button class="px-6 py-2 rounded-xl bg-primary text-white font-medium hover:bg-primary-dark transition-colors">
                    发布
                  </button>
                </div>
              </div>
            </div>
          </div>

          <!-- Posts -->
          <div class="space-y-6">
            <!-- PostCard inline -->
            <div
              v-for="(post, index) in posts"
              :key="index"
              class="bg-surface-light dark:bg-surface-dark rounded-2xl p-6 border border-border-light dark:border-border-dark"
            >
              <div class="flex items-center justify-between mb-4">
                <div class="flex items-center gap-3">
                  <div class="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-primary-dark flex items-center justify-center text-white font-bold">
                    {{ post.avatar }}
                  </div>
                  <div>
                    <h4 class="font-semibold text-text-main dark:text-text-main-dark">{{ post.author }}</h4>
                    <span class="text-xs text-text-secondary dark:text-text-secondary-dark">{{ post.time }}</span>
                  </div>
                </div>
                <button class="p-2 rounded-xl hover:bg-background-light dark:hover:bg-card-dark transition-colors">
                  <MoreHorizontal class="w-5 h-5 text-text-secondary dark:text-text-secondary-dark" />
                </button>
              </div>

              <p class="text-text-main dark:text-text-main-dark mb-4">{{ post.content }}</p>

              <div v-if="post.image" class="rounded-xl overflow-hidden mb-4 bg-gradient-to-br from-primary/20 to-purple-500/20 aspect-video flex items-center justify-center">
                <span class="text-text-secondary dark:text-text-secondary-dark">学习打卡图片</span>
              </div>

              <div class="flex items-center gap-6">
                <button
                  @click="toggleLike(index)"
                  :class="[
                    'flex items-center gap-2 text-sm transition-colors',
                    postLiked[index] ? 'text-red-500' : 'text-text-secondary dark:text-text-secondary-dark hover:text-red-500'
                  ]"
                >
                  <Heart :class="['w-5 h-5', postLiked[index] ? 'fill-current' : '']" />
                  <span>{{ postLikes[index] }}</span>
                </button>
                <button class="flex items-center gap-2 text-sm text-text-secondary dark:text-text-secondary-dark hover:text-primary transition-colors">
                  <MessageSquare class="w-5 h-5" />
                  <span>{{ post.comments }}</span>
                </button>
                <button class="flex items-center gap-2 text-sm text-text-secondary dark:text-text-secondary-dark hover:text-primary transition-colors">
                  <Share2 class="w-5 h-5" />
                  <span>分享</span>
                </button>
              </div>
            </div>
          </div>
        </div>

        <!-- Sidebar -->
        <div class="space-y-6">
          <!-- Trending -->
          <div class="bg-surface-light dark:bg-surface-dark rounded-2xl p-6 border border-border-light dark:border-border-dark">
            <h3 class="font-bold text-text-main dark:text-text-main-dark mb-4 flex items-center gap-2">
              <TrendingUp class="w-5 h-5 text-primary" />
              热门话题
            </h3>
            <div class="space-y-3">
              <div
                v-for="topic in trendingTopics"
                :key="topic.tag"
                class="flex items-center justify-between"
              >
                <span class="text-primary hover:underline cursor-pointer">{{ topic.tag }}</span>
                <span class="text-xs text-text-secondary dark:text-text-secondary-dark">{{ topic.count }} 帖子</span>
              </div>
            </div>
          </div>

          <!-- Active Users -->
          <div class="bg-surface-light dark:bg-surface-dark rounded-2xl p-6 border border-border-light dark:border-border-dark">
            <h3 class="font-bold text-text-main dark:text-text-main-dark mb-4">在线好友</h3>
            <div class="flex -space-x-2">
              <div
                v-for="friend in onlineFriends"
                :key="friend.name"
                class="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-primary-dark flex items-center justify-center text-white font-bold text-sm border-2 border-surface-light dark:border-surface-dark"
                :title="friend.name"
              >
                {{ friend.avatar }}
              </div>
              <div class="w-10 h-10 rounded-full bg-background-light dark:bg-card-dark flex items-center justify-center text-text-secondary dark:text-text-secondary-dark text-xs border-2 border-surface-light dark:border-surface-dark">
                +3
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Leaderboard Tab -->
      <div v-if="activeTab === 'leaderboard'" class="grid lg:grid-cols-3 gap-6">
        <div class="lg:col-span-2">
          <div class="bg-surface-light dark:bg-surface-dark rounded-2xl p-6 border border-border-light dark:border-border-dark">
            <div class="flex items-center justify-between mb-6">
              <h2 class="text-xl font-bold text-text-main dark:text-text-main-dark flex items-center gap-2">
                <Trophy class="w-6 h-6 text-yellow-500" />
                全球排行榜
              </h2>
              <button class="p-2 rounded-xl hover:bg-background-light dark:hover:bg-card-dark transition-colors">
                <Filter class="w-5 h-5 text-text-secondary dark:text-text-secondary-dark" />
              </button>
            </div>

            <div class="space-y-2">
              <!-- LeaderboardRow inline -->
              <div
                v-for="(userItem, index) in globalLeaderboard"
                :key="userItem.name"
                :class="[
                  'flex items-center gap-4 p-4 rounded-xl transition-colors',
                  userItem.isCurrentUser
                    ? 'bg-primary/5 dark:bg-primary/10 border border-primary/20'
                    : 'hover:bg-background-light dark:hover:bg-card-dark'
                ]"
              >
                <div class="w-8 flex justify-center">
                  <Crown v-if="index + 1 === 1" class="w-5 h-5 text-yellow-500" />
                  <Medal v-else-if="index + 1 === 2" class="w-5 h-5 text-gray-400" />
                  <Medal v-else-if="index + 1 === 3" class="w-5 h-5 text-amber-600" />
                  <span v-else class="w-5 text-center font-bold text-text-secondary dark:text-text-secondary-dark">{{ index + 1 }}</span>
                </div>
                <div class="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-primary-dark flex items-center justify-center text-white font-bold text-sm">
                  {{ userItem.avatar }}
                </div>
                <div class="flex-1">
                  <p class="font-medium text-text-main dark:text-text-main-dark">{{ userItem.name }}</p>
                  <p class="text-xs text-text-secondary dark:text-text-secondary-dark">{{ userItem.xp.toLocaleString() }} XP</p>
                </div>
                <div class="flex items-center gap-1 text-orange-500">
                  <Flame class="w-4 h-4" />
                  <span class="text-sm font-medium">{{ userItem.streak }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Sidebar -->
        <div class="space-y-6">
          <!-- Top Performers -->
          <div class="bg-surface-light dark:bg-surface-dark rounded-2xl p-6 border border-border-light dark:border-border-dark">
            <h3 class="font-bold text-text-main dark:text-text-main-dark mb-4">本周之星</h3>
            <div class="space-y-4">
              <div
                v-for="(userItem, index) in globalLeaderboard.slice(0, 3)"
                :key="userItem.name"
                class="flex items-center gap-3"
              >
                <div
                  :class="[
                    'w-8 h-8 rounded-lg flex items-center justify-center font-bold',
                    index === 0 ? 'bg-yellow-100 text-yellow-600' :
                    index === 1 ? 'bg-gray-100 text-gray-600' :
                    'bg-amber-100 text-amber-600'
                  ]"
                >
                  {{ index + 1 }}
                </div>
                <div class="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-primary-dark flex items-center justify-center text-white font-bold text-sm">
                  {{ userItem.avatar }}
                </div>
                <div class="flex-1">
                  <p class="font-medium text-text-main dark:text-text-main-dark text-sm">{{ userItem.name }}</p>
                  <p class="text-xs text-text-secondary dark:text-text-secondary-dark">{{ userItem.xp.toLocaleString() }} XP</p>
                </div>
                <Star
                  :class="[
                    'w-5 h-5',
                    index === 0 ? 'text-yellow-500 fill-current' :
                    index === 1 ? 'text-gray-400' :
                    'text-amber-600'
                  ]"
                />
              </div>
            </div>
          </div>

          <!-- Your Progress -->
          <div class="bg-surface-light dark:bg-surface-dark rounded-2xl p-6 border border-border-light dark:border-border-dark">
            <h3 class="font-bold text-text-main dark:text-text-main-dark mb-4">你的进度</h3>
            <div class="space-y-4">
              <div>
                <div class="flex justify-between text-sm mb-1">
                  <span class="text-text-secondary dark:text-text-secondary-dark">距离前一名</span>
                  <span class="font-medium text-text-main dark:text-text-main-dark">560 XP</span>
                </div>
                <div class="h-2 bg-background-light dark:bg-card-dark rounded-full overflow-hidden">
                  <div class="w-3/4 h-full bg-primary rounded-full" />
                </div>
              </div>
              <div class="flex items-center justify-between p-3 rounded-xl bg-background-light dark:bg-card-dark">
                <span class="text-text-secondary dark:text-text-secondary-dark">本周排名变化</span>
                <span class="text-green-500 font-medium flex items-center gap-1">
                  <TrendingUp class="w-4 h-4" />
                  +12
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import {
  Users,
  Search,
  MessageCircle,
  UserPlus,
  Trophy,
  Flame,
  TrendingUp,
  MoreHorizontal,
  Heart,
  Share2,
  MessageSquare,
  Filter,
  Medal,
  Crown,
  Star,
} from 'lucide-vue-next';
import { useAppStore } from '../stores/appStore';

const store = useAppStore();
const activeTab = ref<'friends' | 'feed' | 'leaderboard'>('friends');
const searchQuery = ref('');

const tabs = [
  { id: 'friends' as const, label: '好友', icon: Users },
  { id: 'feed' as const, label: '动态', icon: MessageSquare },
  { id: 'leaderboard' as const, label: '排行榜', icon: Trophy },
];

const friends = [
  { name: 'Sarah Chen', avatar: 'S', level: 15, xp: 2890, streak: 45, isOnline: true },
  { name: 'Mike Ross', avatar: 'M', level: 12, xp: 2450, streak: 12, isOnline: true },
  { name: 'Kenji Sato', avatar: 'K', level: 10, xp: 1920, streak: 3, isOnline: false, lastActive: '2小时前' },
  { name: 'Emma Wilson', avatar: 'E', level: 9, xp: 1850, streak: 8, isOnline: false, lastActive: '5小时前' },
  { name: 'David Kim', avatar: 'D', level: 8, xp: 1680, streak: 15, isOnline: true },
  { name: 'Lisa Wang', avatar: 'L', level: 7, xp: 1520, streak: 6, isOnline: false, lastActive: '1天前' },
];

const suggestedFriends = [
  { name: 'Anna Lee', avatar: 'A', level: 11 },
  { name: 'Chris Park', avatar: 'C', level: 9 },
  { name: 'Yuki Tanaka', avatar: 'Y', level: 8 },
];

const posts = [
  {
    author: 'Sarah Chen',
    avatar: 'S',
    content: '今天完成了30个单词的学习！坚持就是胜利 💪 #英语学习 #每日打卡',
    likes: 24,
    comments: 5,
    time: '2小时前',
    liked: true,
  },
  {
    author: 'Mike Ross',
    avatar: 'M',
    content: '终于突破了连续学习30天的里程碑！感谢LinguaAI的陪伴 🎉',
    image: 'milestone',
    likes: 56,
    comments: 12,
    time: '5小时前',
  },
  {
    author: 'Kenji Sato',
    avatar: 'K',
    content: '今天的AI对话练习很有帮助，纠正了我很多发音问题。推荐给所有正在学习的朋友！',
    likes: 18,
    comments: 3,
    time: '昨天',
  },
];

const trendingTopics = [
  { tag: '#每日打卡', count: '12.5k' },
  { tag: '#英语角', count: '8.2k' },
  { tag: '#学习方法', count: '6.8k' },
  { tag: '#AI对话', count: '5.4k' },
  { tag: '#词汇记忆', count: '4.1k' },
];

const user = computed(() => store.user);
const stats = computed(() => store.stats);

const globalLeaderboard = [
  { name: 'Alex Johnson', avatar: 'A', xp: 15200, streak: 156 },
  { name: 'Maria Garcia', avatar: 'M', xp: 14800, streak: 142 },
  { name: 'James Wilson', avatar: 'J', xp: 13500, streak: 98 },
  { name: 'Sophie Chen', avatar: 'S', xp: 12200, streak: 87 },
  { name: 'Tom Brown', avatar: 'T', xp: 11800, streak: 76 },
  { name: 'Sarah Chen', avatar: 'S', xp: 2890, streak: 45 },
  { name: 'Mike Ross', avatar: 'M', xp: 2450, streak: 12 },
  { name: user.value?.name || 'You', avatar: (user.value?.name?.[0] || 'Y'), xp: stats.value.totalXP, streak: stats.value.streakDays, isCurrentUser: true },
];

const filteredFriends = computed(() =>
  friends.filter(f => f.name.toLowerCase().includes(searchQuery.value.toLowerCase()))
);

const onlineFriends = computed(() => friends.filter(f => f.isOnline));

// Post like state
const postLiked = ref(posts.map(p => p.liked));
const postLikes = ref(posts.map(p => p.likes));

const toggleLike = (index: number) => {
  if (postLiked.value[index]) {
    postLikes.value[index]--;
  } else {
    postLikes.value[index]++;
  }
  postLiked.value[index] = !postLiked.value[index];
};
</script>
